### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ziondh7** [lay295/KickDownloader#1]
Error after I download the it does not work

**Comment by lay295** [comment]
At one point TwitchDownloader will support kick whenever I get around to it.

Not sure what issue you're having with this provided the little information given. I see Kick has updated their clip format so I made a new release that can parse it correctly.

Or perhaps you downloaded the .exe I had uploaded instead of the .zip and you didn't have ffmpeg. If that's the case try downloading 1.01 and extracting the zip file and running the exe. Should work.
